[package]
name = "viaptr"
version = "0.1.0"
edition = "2021"

[dependencies]
triomphe = { version = "0.1.11", optional = true, default-features = false }

[features]
default = ["std"]
std = []

[dev-dependencies]
proptest = "1.4.0"
