blank_lines_upper_bound = 2
combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 100
spaces_around_ranges = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
